const ActionType = {
    ADD_FORM_ITEM: 'ADD_FORM_ITEM',
    DELETE_FORM_ITEM: 'DELETE_FORM_ITEM',
    IS_DRAGING_ITEM: 'IS_DRAGING_ITEM',
    UPDATE_ITEM_CONFIG: 'UPDATE_ITEM_CONFIG',
    IMPORT_FORM_ITEMS: 'IMPORT_FORM_ITEMS',

    CLEAR_FORM_ITEMS_VALUE: 'CLEAR_FORM_ITEMS_VALUE',
    
    UPDATE_BTN_CONFIG_PROPS: 'UPDATE_BTN_CONFIG_PROPS',
    UPDATE_INPUT_CONFIG_PROPS: 'UPDATE_INPUT_CONFIG_PROPS',
    UPDATE_TEXTAREA_CONFIG_PROPS: 'UPDATE_TEXTAREA_CONFIG_PROPS',
    UPDATE_SELECT_CONFIG_PROPS: 'UPDATE_SELECT_CONFIG_PROPS',
    UPDATE_CHECKBOX_CONFIG_PROPS: 'UPDATE_CHECKBOX_CONFIG_PROPS',
    UPDATE_RADIO_CONFIG_PROPS: 'UPDATE_RADIO_CONFIG_PROPS',
    UPDATE_SWITCH_CONFIG_PROPS: 'UPDATE_SWITCH_CONFIG_PROPS',
    UPDATE_UPLOAD_CONFIG_PROPS: 'UPDATE_UPLOAD_CONFIG_PROPS',
    UPDATE_RANGE_CONFIG_PROPS: 'UPDATE_RANGE_CONFIG_PROPS',
    UPDATE_DATE_CONFIG_PROPS: 'UPDATE_DATE_CONFIG_PROPS',

    SUBMIT_DATA: 'SUBMIT_DATA',
    DRAG_UPDATE: 'DRAG_UPDATE'
  };
  
  export default ActionType;